### ISSUE TITLE
Add numbered version tags to the Docker images

### ISSUE THREAD

**Issue by bcb** [olesku/eventhub#36]
I'd like to pin my Eventhub image to a specific version number, e.g. `eventhub:1`. With the existing tags, they might be version 1 right now but it could be version 2 later when I'm not ready to upgrade.

<img width="223" alt="Screen Shot 2021-12-21 at 8 37 46 am" src="https://user-images.githubusercontent.com/134581/146836079-c47d00dd-d8e3-452d-b6fd-77aad7620b81.png">

**Comment by olesku** [comment]
Hi,

Thanks for reaching out.

You are right, those tags should absolutely be up to date with the current releases.
Right now this is a manual process, but the plan is to automate this GitHub actions so that we will build and deploy a release docker image each time a new release is created.

For now I've added the tags for the v1.0.0 release and updated the stable and latest tag accordingly.

![2021-12-21-122502_265x174_scrot](https://user-images.githubusercontent.com/3126663/146922488-f396f682-860a-43c3-9970-bd0122db09fb.png)
